.Dd Apr 18, 2024
.Dt BIGOTES 1
.Os
.Sh NAME
.Nm bigotes
.Nd benchmark measurement tool
.Sh SYNOPSIS
.Nm bigotes
.Op Ar options
.Op Fl -
.Ar command
.Op Ar args...
.Nm bigotes
.Op Ar options
.Fl s Ar script
.Nm bigotes
.Op Ar options
.Fl i
.Sh DESCRIPTION
The
.Nm
program is a versatile tool designed to perform automatic benchmark
measurements and report statistical information. A single quantity is
sampled multiple times by either running again a given program or by
reading the values from the standard input. The typical quantity 
is the execution time, but others can be used too.
.Pp
The execution of the program is repeated until at least 30 samples are
collected, 30 seconds have elapsed and the Standard Error of the Mean
(SEM) is small.
All those criteria must be met to stop collecting samples.
.Pp
At the end, a summary is shown with the number of samples collected
(RUN), the execution time (WALL), the five-number summary (MIN, Q1,
MEDIAN, Q3, MAX), the median average deviation (MAD), the relative MAD
to the median (%MAD) and the relative standard error of the mean (%SEM).
An histogram is plotted by using UTF-8 block characters and the results
of the Shapiro-Wilk test for normality.
.Pp
There are three modes of operation and one must be selected.
.Bl -tag -width Ds
.It Fl -
Selects the
.Em exec
mode (the default). Runs the command and arguments as-is, without a shell. The 
.Fl -
flag may be omitted.
.It Fl s
Selects the
.Em shell
mode. Runs the
.Ar script
in a shell, performing the shell substitution as
necessary. Allows processing the output with a pipe, but requires
escaping quotes.
.It Fl i
Selects the
.Em stdin
mode. Reads quantities values from the standard input, one per line.
Nothing is executed in this mode.
.El
.Pp
The
.Ar options
must precede the operation mode and are as follows:
.Bl -tag -width Ds
.It Fl o Ar file
Write the measured quantities in the given
.Ar file ,
one per line. Not compatible with the stdin mode.
.It Fl q
Be quiet, don't report progress information during execution.
.It Fl w
Instead of reading the quantity from the standard output, use the
wall clock time (in seconds) that the program took to run. Not
compatible with the stdin mode.
.El
.Pp
The name
.Nm
comes from the Spanish word for whiskers which are commonly used in
statistics to represent the dispersion of a sample when drawing box
plots or error bars.
.Sh EXIT STATUS 
.Ex -std
.Sh EXAMPLES
Run the b6_heat_nanos6 benchmark with the given parameters in a remote
machine by using srun:
.Bd -literal
$ srun -u -c56 bigotes b6_heat_nanos6 -s 1024 -t 10 -b 64
  RUN   WALL       MIN        Q1    MEDIAN        Q3       MAX       MAD   %MAD   %SEM  OUTLIERS
  326   30.0  1.03e-02  1.32e-02  1.34e-02  1.35e-02  1.42e-02  1.35e-04   1.01   0.15        34

                                                        █
                                                      ▃▃███
                                                      █████▁
                                                     ▄██████▁
                                                     ████████
                                                    █████████
                                                    █████████▄
 ▄▁▆▄▁▃▄▄▃ ▁     ▁  ▁ ▃▄▁▁  ▁▁                  ▄▁▄███████████▃▃▄▃▃▁  ▁

Shapiro-Wilk: W=5.67e-01, p-value=1.15e-27 (NOT normal)
.Ed

Ping a remote host and take the time as the measurement using a pipe
(note the escaping for the shell):
.Bd -literal
$ bigotes -s "ping -c 1 1.1.1.1 | awk -F'=' '/time=/ { print \\$4 }' | cut -d' ' -f1"
  RUN   WALL       MIN        Q1    MEDIAN        Q3       MAX       MAD   %MAD   %SEM  OUTLIERS
  914   30.0  1.72e+01  1.85e+01  1.91e+01  1.96e+01  4.30e+01  5.00e-01   2.62   0.26        11

     ▁█
     ██
   ▁ ██▁
   █▅███▁
   ██████
   ██████
  ▄██████▅
 ▂████████▃▂▂▁▁   ▁ ▁▁ ▁   ▁ ▁                   ▁                    ▁

Shapiro-Wilk: W=5.47e-01, p-value=2.60e-43 (NOT normal)
.Ed

Read the measurements from the standard input, generated by a Gaussian
distribution using the gsl-randist tool:
.Bd -literal
% gsl-randist 0 500 gaussian 0.5 | bigotes -i
  RUN   WALL       MIN        Q1    MEDIAN        Q3       MAX       MAD   %MAD   %SEM  OUTLIERS
  500    0.0  -1.34e+00  -3.11e-01  1.78e-03  3.57e-01  1.67e+00  3.33e-01  18665.43  162.80         0

                        ▂     █▂ ▂  █
                        █▇   ▇██▄█  █ ▁
                        ██ ▁ █████▁▁█ █ ▆▃
                    ▂▅▅▅██▂█▅████████ █ ██   ▅
                    █████████████████ █ ██ ▂▅█
               ▁▁▄  █████████████████▇█▇██▄███▄▄▇▄  ▄
    ▁▁    ▁ ▆▁▁███▃▆██████████████████████████████ ▆█ ▃   ▁
 ▅▂▂██▂▂ ▂█ ██████████████████████████████████████▅██▅█▂▅▅█▂▂▂ ▂ ▅

Shapiro-Wilk: W=9.97e-01, p-value=4.11e-01 (may be normal)
.Ed

.Sh SEE ALSO
.Pp
The repository 
.Lk https://github.com/rodarima/bigotes/
contains the last version of the program.
.Sh AUTHORS
.An "Rodrigo Arias Mallo" Aq Mt "rodrigo.arias@bsc.es"
